api:
  dashboard: true

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

certificatesResolvers:
  resolver:
    acme:
      email: daniel.hrovinsky@gmail.com
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web
        
providers:
  file:
    directory: /etc/traefik/routing

log:
  format: common
  level: DEBUG

accessLog: {}