name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: eu-central-1                 
  FRONTEND_ECR_REPOSITORY: frontend  
  BACKEND_ECR_REPOSITORY: backend

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$FRONTEND_ECR_REPOSITORY:latest https://github.com/nodari-dev/int20h-edu-network.git#master
        docker push $ECR_REGISTRY/$FRONTEND_ECR_REPOSITORY:latest
        echo "image=$ECR_REGISTRY/$FRONTEND_ECR_REPOSITORY:latest" >> $GITHUB_OUTPUT
        docker build -t $ECR_REGISTRY/$BACKEND_ECR_REPOSITORY:latest https://github.com/Danchikon/edupulse.backend.git#main
        docker push $ECR_REGISTRY/$BACKEND_ECR_REPOSITORY:latest
        echo "image=$ECR_REGISTRY/$BACKEND_ECR_REPOSITORY:latest" >> $GITHUB_OUTPUT

    
